### ISSUE TITLE
Bitwig cc 121 error

### ISSUE THREAD

**Issue by KingRoy84** [MircoL/steinberg-cc121-bitwig#2]
Can you fix this ?

CC121 Crashed

TypeError: invokeMember (sendMidi) on com.bitwig.flt.control_surface.proxy.MidiOutPort@5ebca7d failed due to: Cannot convert '26.974114535112676' (language: Java, type: java.lang.Double) to Java type 'int': Invalid or lossy primitive correction 

and 

CC121 Crashed

TypeError: invokeMember (sendMidi) on com.bitwig.flt.control_surface.proxy.MidiOutPort@7e8ee177 failed due to: Cannot convert '26.974114535112676' (language: Java, type: java.lang.Double) to Java type 'int': Invalid or lossy primitive correction 

Kind Regards, 

Roy

**Comment by xanthos84** [comment]
If someone else gets this error, its easy to fix in SteinbergCC121.channel.js file - search for line 61 and change to:
`    trackBank.getChannel(0).volume().value().addValueObserver(function(volumeValue) {
        var LSB = parseInt((volumeValue * 16383) % 128);
        var MSB = parseInt((volumeValue * 16383) / 128);
        sendMidi(224, LSB, MSB);
    });`

**Comment by MircoL** [comment]
Fixed in 5bcb9a42c08373f55554d928153f1e0d839c85cf. Thanks @xanthos84
